package main

import (
	"bufio"
	"bytes"
	"context"
	"flag"
	"fmt"
	"go/format"
	"io"
	"log/slog"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"unicode/utf8"
)

func main() {
	if err := run(context.Background(), os.Args[1:]); err != nil {
		slog.Error("run", "err", err)
		os.Exit(1)
	}
}

func run(ctx context.Context, args []string) error {
	var (
		src     string
		out     string
		pkgName string
	)

	fs := flag.NewFlagSet("emoji", flag.ContinueOnError)
	fs.StringVar(&src, "src", "https://unicode.org/Public/emoji/latest/emoji-test.txt", "emoji data source")
	fs.StringVar(&out, "out", "./emoji/emoji_gen.go", "output file path")
	fs.StringVar(&pkgName, "pkg", "emoji", "package name to use in the generated file")

	if err := fs.Parse(args); err != nil {
		return fmt.Errorf("parse flags: %w", err)
	}

	emojis, err := loadEmoji(ctx, src)
	if err != nil {
		return fmt.Errorf("load emoji: %w", err)
	}

	data, err := generateSource(pkgName, emojis)
	if err != nil {
		return fmt.Errorf("generate source: %w", err)
	}

	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}

	if err := os.WriteFile(out, data, 0o644); err != nil {
		return fmt.Errorf("write output: %w", err)
	}

	return nil
}

func loadEmoji(ctx context.Context, src string) ([]string, error) {
	reader, err := openSource(ctx, src)
	if err != nil {
		return nil, err
	}
	defer reader.Close()

	return parseEmojiTest(reader)
}

func openSource(ctx context.Context, src string) (io.ReadCloser, error) {
	parsed, err := url.Parse(src)
	if err == nil && (parsed.Scheme == "http" || parsed.Scheme == "https") {
		req, err := http.NewRequestWithContext(ctx, http.MethodGet, src, nil)
		if err != nil {
			return nil, fmt.Errorf("new request: %w", err)
		}

		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			return nil, fmt.Errorf("request source: %w", err)
		}
		if resp.StatusCode != http.StatusOK {
			resp.Body.Close()
			return nil, fmt.Errorf("request source: unexpected status %s", resp.Status)
		}

		return resp.Body, nil
	}

	file, err := os.Open(src)
	if err != nil {
		return nil, fmt.Errorf("open source: %w", err)
	}

	return file, nil
}

func parseEmojiTest(reader io.Reader) ([]string, error) {
	scanner := bufio.NewScanner(reader)
	scanner.Buffer(make([]byte, 1024), 1024*1024)

	set := map[string]struct{}{}
	for lineNumber := 1; scanner.Scan(); lineNumber++ {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		body, _, _ := strings.Cut(line, "#")
		codePointsField, statusField, ok := strings.Cut(body, ";")
		if !ok {
			return nil, fmt.Errorf("line %d: missing status", lineNumber)
		}

		status := strings.TrimSpace(statusField)
		if status != "component" && status != "fully-qualified" {
			continue
		}

		emoji, err := parseCodePoints(strings.Fields(codePointsField))
		if err != nil {
			return nil, fmt.Errorf("line %d: %w", lineNumber, err)
		}

		set[emoji] = struct{}{}
	}

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("scan source: %w", err)
	}

	emojis := make([]string, 0, len(set))
	for emoji := range set {
		emojis = append(emojis, emoji)
	}
	slices.Sort(emojis)

	if len(emojis) == 0 {
		return nil, fmt.Errorf("no emojis found")
	}

	return emojis, nil
}

func parseCodePoints(codePoints []string) (string, error) {
	if len(codePoints) == 0 {
		return "", fmt.Errorf("missing code points")
	}

	var builder strings.Builder
	for _, codePoint := range codePoints {
		value, err := strconv.ParseInt(codePoint, 16, 32)
		if err != nil {
			return "", fmt.Errorf("parse code point %q: %w", codePoint, err)
		}

		r := rune(value)
		if !utf8.ValidRune(r) {
			return "", fmt.Errorf("invalid rune %q", codePoint)
		}

		builder.WriteRune(r)
	}

	return builder.String(), nil
}

func generateSource(pkgName string, emojis []string) ([]byte, error) {
	var buffer bytes.Buffer

	buffer.WriteString("// Code generated by go run ./cmd/emoji; DO NOT EDIT.\n")
	buffer.WriteString("package ")
	buffer.WriteString(pkgName)
	buffer.WriteString("\n\n")
	buffer.WriteString("var validSet = map[string]struct{}{\n")
	for _, emoji := range emojis {
		fmt.Fprintf(&buffer, "\t%q: {},\n", emoji)
	}
	buffer.WriteString("}\n\n")
	buffer.WriteString("func IsValid(text string) bool {\n")
	buffer.WriteString("\t_, ok := validSet[text]\n")
	buffer.WriteString("\treturn ok\n")
	buffer.WriteString("}\n")

	formatted, err := format.Source(buffer.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format source: %w", err)
	}

	return formatted, nil
}
